name: CI

on:
  push:
  pull_request:
  workflow_dispatch:


jobs:
  protoc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
      
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19.1'
          check-latest: true

      - name: Install protoc plugins
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2

      - name: Build protos for go
        run: |
          mkdir go-protos
          protoc --proto_path . \
            --go_out=module=github.com/redmcme/go-protos:./go-protos \
            --go-grpc_out=module=github.com/redmcme/go-protos:./go-protos \
            ./*/**
          
      - uses: actions/upload-artifact@v3
        with:
          name: go-protos 
          path: go-protos
